config/routes.rb
BootBook::Application.routes.draw do

  resources :users
  post '/request_friend/:id' => 'users#request_friend'
  post '/approve_friend/:id' => 'users#approve_friend'
  post '/deny_friend/:id' => 'users#deny_friend'
  get '/logout' => 'users#logout'
  post '/login' => 'users#login'
  post '/status_update/:id' => 'users#status_update'
  post '/add_comment/:wall_owner_id/:parent_id' => 'users#add_comment'
  post '/like_item/:item_id' => 'users#like_item'
  root to: 'welcome#index'

end

app/models/Cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :cohort_name, :start_date, :end_date
  validates :cohort_name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/User.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :first_name, :last_name, :email, :password, :birthdate, :cohort_id, :interest
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :birthdate, :presence => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :cohort_id, :presence => true
  validates :interest, :presence => true
end

app/models/cohort.rb
 class Cohort < ActiveRecord::Base
  has_many :students, class_name: "User"
  attr_accessible :cohort_name, :start_date, :end_date
  validates :cohort_name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, foreign_key: "user_id"
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"

  validates :user_id, presence: true
  validates :friend_id, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base

  before_save :check_type

  attr_accessible :item_type, :content
  belongs_to :wall_owner, class_name: "User", foreign_key: "wall_owner_id"
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :comments, class_name: "Item", foreign_key: "relation_id"
  belongs_to :parent, class_name: "Item", foreign_key: "relation_id"

  validates_presence_of :user_id, :item_type, :content
  validates :item_type, inclusion: { in: %w(status comment), message: "%(value) is not a valid item type" }

  acts_as_likeable

  private

  def check_type
    case item_type
    when "status"
      self.parent = nil
    when "comment"
      self.comments = []
    end
  end

end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/pending_friendship.rb
class PendingFriendship < ActiveRecord::Base

  belongs_to :user, foreign_key: "user_id"
  belongs_to :pending_friend, class_name: "User", foreign_key: "pending_friend_id"

  validates :user_id, presence: true
  validates :pending_friend_id, presence: true
  validates_uniqueness_of :pending_friend_id, scope: :user_id

  def approve!
    friendship = Friendship.new
    friendship.user_id = self.user_id
    friendship.friend_id = self.pending_friend_id
    friendship.save!
    friendship = Friendship.new
    friendship.user_id = self.pending_friend_id
    friendship.friend_id = self.user_id
    friendship.save!
    self.destroy
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :status, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships, foreign_key: "user_id", class_name: "Friendship"
  has_many :friends, through: :friendships
  has_many :pending_friendships, foreign_key: "user_id", class_name: "PendingFriendship"
  has_many :pending_friends, through: :pending_friendships
  has_many :items
  belongs_to :cohort

  has_secure_password
  attr_accessible :first_name, :last_name, :email, :password, :birthdate, :cohort_id, :interest
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :birthdate, :presence => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :cohort_id, :presence => true
  validates :interest, :presence => true

  acts_as_liker

  def accept_friend(friend_id)
    request = self.pending_friendships.find_by_pending_friend_id(friend_id)
    request.approve!
  end

  def deny_friend(friend_id)
    request = self.pending_friendships.find_by_pending_friend_id(friend_id)
    request.destroy
  end
end

app/controllers/application_controller.rb
require 'application_helper'
require 'users_helper'
class ApplicationController < ActionController::Base
  include ApplicationHelper
  include UsersHelper
  protect_from_forgery
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def create
    render params.inspect
  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def login
    if @user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @error = "We were unable to find that email and password combination."
      render 'welcome/index'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :root
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def show
    @user = User.find(params[:id])
  end

  def request_friend
    @pending_friend = User.find(params[:id])
    @pending_friend.pending_friends << User.find(session[:user_id])
    redirect_to users_path
  end

  def approve_friend
    @user = User.find(session[:user_id])
    @user.accept_friend(params[:id])
    redirect_to user_path(@user)
  end

  def deny_friend
    @user = User.find(session[:user_id])
    @user.deny_friend(params[:id])
    redirect_to user_path(@user)
  end

  def update
    @user = User.find(session[:user_id])
    # if @user.save
    @user.update_attributes(params[:user])
    if request.xhr?
      render 'show', layout: false
    else
      redirect_to user_path(@user)
    end
    # else
    #   render 'new'
  end
  # end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
  end

  def status_update
    @item = current_user.items.new(content: params[:status],
      item_type: "status")
    @item.wall_owner_id = params[:id]
    if @item.save
      redirect_to user_path(params[:id])
    else
      render 'show'
    end
  end

  def add_comment
    @comment = current_user.items.create(content: params[:comment],
      item_type: "comment")
    @comment.wall_owner_id = params[:wall_owner_id]
    @comment.relation_id = params[:parent_id]
    if @comment.save
      redirect_to user_path(params[:wall_owner_id])
    else
      params[:id] = params[:wall_owner_id]
      render 'show'
    end
  end

  def like_item
    @item = Item.find(params[:item_id])
    current_user.toggle_like!(@item)
    if @item.item_type == "comment"
      redirect_person = @item.parent.wall_owner
    elsif @item.item_type == "status"
      redirect_person = @item.wall_owner
    end
    redirect_to user_path(redirect_person)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return User.find(session[:user_id]) if session[:user_id]
    nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def requested_friends
    @pending_friendships = PendingFriendship.where(pending_friend_id: current_user.id)
    @users = []
    @pending_friendships.each do |pending_friendship|
      @users << User.find(pending_friendship.user_id)
    end
    @users
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/items/_status.html.erb
<h4><a href=<%= user_path(@status.user_id) %>><%= User.find(@status.user_id).first_name %></a>: <%= @status.content %></h4>
<div class="likes"><%= @status.likers(User).count %> likes</div>
<div class="like_status_button">
<%= form_tag("/like_item/#{@status.id}", method: "post") do %>
<% if @status.liked_by?(current_user) %>
<%= submit_tag("UNLIKE IT") %>
<% else %>
<%= submit_tag("LIKE IT") %>
<% end %>
<% end %>
</div>
<ul>
  <% @status.comments.each do |comment| %>
  <div class="comments">
    <li><%= link_to User.find(comment.user_id).first_name, user_path(User.find(comment.user_id)) %> <%= comment.content %>
      <div class="likes">
        <%= comment.likers(User).count %> likes
      </div>
      <div class="like_comment_button">
      <%= form_tag("/like_item/#{comment.id}", method: "post") do %>
      <% if comment.liked_by?(current_user) %>
      <%= submit_tag("UNLIKE IT") %>
      <% else %>
      <%= submit_tag("LIKE IT") %>
      <% end %>
      </div>
    </li>
  </div>
  <% end %>

  <% end %>
</ul>
<% @status%>
<%= form_tag("/add_comment/#{@status.wall_owner_id}/#{@status.id}", method: "post") do %>
<%= label_tag(:comment, "Comment:") %>
<%= text_field_tag(:comment) %>
<%= submit_tag("comment") %>
<% if @comment %>
<% if @comment.errors.any? %>
<div class="errorExplanation">
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%=msg%></li>
    <% end %>
  </div>
  <% end %>
  <% end %>
  <% end %>

app/views/items/_statuses.html.erb
<% @statuses = Item.where(wall_owner_id: params[:id]).where(item_type: "status") %>
<% if @statuses %>
<% @statuses.reverse.each do |status| %>
<% @status = status %>
<div class="status">
<%= render partial: 'items/status' %>
</div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" %>
  <header>
    <nav id="navigation">
        <%= link_to image_tag('bootbook.png'), root_path %>
        <% if current_user %>
        <%= link_to "Log out", logout_path, style:"float:right;" %>
        <% end %>
    </div>
  </header>
</head>
<body>
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_create_status.html.erb
<div id="status_div">
  <%= form_for :status, url: statuses_path do |f| %>
    <%= f.text_field  :status, id: "status", placeholder: "What's on your mind?" %>
  <br>
  <%= f.submit "Post", id: "post_status_button" %>
  <% end %>
</div>

app/views/users/_friend_status.html.erb
<h3><%= @friend.first_name %> </h4>
<h5> Banana! </h5>
<h6> Update this in <strong>app/users/_friend_status.html.erb</strong> when status' are available</h6>

app/views/users/_friends.html.erb
<% @friends.each do |friend| %>
<% @friend = friend %>
<%= render 'friend_status' %>
<% end %>

app/views/users/_friends_list.html.erb
<% @user.friends.each do |friend| %>
  <div class="friend" >
  <% @user = friend %>
  <%= render 'user_profile' %>
  <%= link_to "Profile", user_path(@user) %>
</div>
  <% end %>
<% @user = params[:id] %>

app/views/users/_pending_friend_requests.html.erb
<br><br>
<% pending_friends = @user.pending_friends.each do |pending_friend| %>
<%= "#{pending_friend.first_name} #{pending_friend.last_name}" %>
    <%= form_tag("/approve_friend/#{pending_friend.id}", method: "post") do %>
    <%= submit_tag("add friend") %>
  <% end %>

  <%= form_tag("/deny_friend/#{pending_friend.id}", method: "post") do %>
    <%= submit_tag("deny friend") %>
  <% end %>
<% end %>

app/views/users/_user_profile.html.erb
<div class="mini_profile">

  <h1>
    <% if @user == current_user && params[:id].to_i == current_user.id  %>
    <span id="user_grav"><%= gravatar_for @user %></span>
    <% else %>
<%= gravatar_for @user %>
    <% end %>
    <% if @user == current_user && params[:id].to_i == current_user.id %>
    <p>Don't like this picture? Want to change it? <a href="https://en.gravatar.com/site/signup/">Click Here!</a></p>
    <% end %>
  </h1>

  <h3>Name: <%= @user.first_name%> <%= @user.last_name %></h3>
  <h3>Email: <%= @user.email %></h3>
  <h3>interests: <%= @user.interest %></h3>
  <% if current_user == @user && params[:id].to_i == current_user.id  %>
  <span id="friends"><%= link_to "Find Your Friends", users_path %></span>
  <% end %>
</div>

app/views/users/_user_status_feed.html.erb
  <div class="status_feed" >
    <div class="update_status">
    <h3> STATUS FEED </h3>
      <% if User.find(params[:id]).friends.include?(current_user) || User.find(params[:id]) == current_user %>
      <%= form_tag("/status_update/#{params[:id]}", method: "post") do %>
      <%= label_tag(:status, "Update Status:") %>
      <%= text_field_tag(:status) %>
      <%= submit_tag("update status") %>
      <% if @item %>
      <% if @item.errors.any? %>
      <div class="errorExplanation">
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
          <li><%=msg%></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </div>
    <%= render partial: "items/statuses" %>
    </div>
    <div class="friend_list">
      <%= render 'friends_list' %>
  </div>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
  <div class="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error")%> prevented your account from being created.</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %>
  </div>
<% end %>
  First name: <%= f.text_field  :first_name %><br>
  Last name:  <%= f.text_field  :last_name  %><br>
  Birthdate:  <%= f.date_select :birthdate %><br>
  Cohort: <%= select(:user, :cohort_id, Cohort.all.collect { |p| [p.cohort_name, p.id]}, {prompt: "Select your cohort"}) %><br>
  Interest:   <%= f.text_area   :interest   %><br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
  <% (User.all - @user.friends - requested_friends - [@user]).each do |user| %>
  <% @user = user %>
  <%= render 'user_profile' %>
  <br>
    <%= form_tag("/request_friend/#{@user.id}", method: "post") do %>
    <%= submit_tag("add friend") %>
  <% end %>
<% end %>
<%= link_to "Back to your Profile", user_path(current_user) %>

app/views/users/new.html.erb
<%= form_for :user, url: '/users', html: {id: "sign_up"} do |f| %>
<% if @user.errors.any? %>
  <div class="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error")%> prevented your account from being created.</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %>
  </div>
<% end %>
  First name: <%= f.text_field  :first_name %><div class="error" id="error_name">First Name required!</div><br>
  Last name:  <%= f.text_field  :last_name  %><div class="error" id="error_last_name">Last Name required!</div><br>
  Password:   <%= f.password_field    :password   %><div class="error" id="error_password">Password required!</div><br>
  Email:      <%= f.text_field  :email      %><div class="error" id="error_email">First Email required!</div><br>
  Birthdate:  <%= f.date_select :birthdate %><br>
  Cohort: <%= select(:user, :cohort_id, Cohort.all.collect { |p| [p.cohort_name, p.id]}, {prompt: "Select your cohort"}) %><br>
  Interest:   <%= f.text_area   :interest   %><div class="error" id="error_interest">Gotta have some...</div><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="user_splash">
<% if current_user == @user %>
<h1>Hey there, <%= @user.first_name %>!</h1>
<% end %>
<div class="profile_user">
  <% @user = User.find(params[:id]) %>
<%= render 'user_profile' %>
</div><br>
<% if current_user == @user %>
<div class="profile_options">
<%= link_to "Edit your Profile", edit_user_path(current_user), :id => 'edit-profile' %> |
<%= link_to "Deauthorize your Account", user_path(current_user), :method=>:delete, data: { confirm: "Are you sure? This is permanent" } %> |
</div>
<% end %>
</div>
<%= render 'pending_friend_requests' %>
<%= render 'user_status_feed' %>

app/views/welcome/index.html.erb
<div class="splash">
<div class="splash_inputs">
<%= link_to "Sign up!", new_user_path %>

<% if @error %>
  <div class="errorExplanation"><%=@error%></div>
<% end %>
<%= form_tag (login_path), id: "login" %>

  Email: <%= text_field_tag  :email  %><br>
  Password: <%= password_field_tag :password %><br>
  <%= submit_tag "Login", style: "float: left;" %>
</div>
</div>